# Generated by Django 2.2.17 on 2020-12-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('local', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesess', models.CharField(choices=[('Estágio', 'Estágio'), ('CLT', 'CLT'), ('PJ', 'PJ')], default='Estágio', max_length=255)),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('resumo', models.CharField(max_length=255)),
                ('experiencia_profissional', models.TextField()),
                ('cursos', models.TextField()),
                ('idiomas', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
