# Generated by Django 3.1.4 on 2020-12-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='cadastro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculo', to='cadastro.cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='data_de_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
