# Generated by Django 2.2.17 on 2021-01-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave_api',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rest_framework_api_key.APIKey'),
        ),
    ]
