# Generated by Django 3.1.4 on 2020-12-09 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0002_auto_20201209_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadastro', to='auth.user'),
            preserve_default=False,
        ),
    ]
