# Generated by Django 2.2.17 on 2020-12-11 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0003_cadastro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='user',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='cadastro',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='nome',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='interesess',
            field=models.CharField(choices=[('Estágio', 'Estágio'), ('CLT', 'CLT'), ('PJ', 'PJ')], default='Estágio', max_length=255),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='user',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
