# Generated by Django 2.2.17 on 2020-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='interesess',
            field=models.CharField(choices=[('Estágio', 'Estágio'), ('CLT', 'CLT'), ('PJ', 'PJ')], default='Estágio', max_length=255),
        ),
    ]
